version: 0.0
os: linux
files:
  - source: /
    destination: /home/ssungis/apiGateway/board

hooks:
  AfterInstall:
    - location: /home/ssungis/apiGateway/board/board-deploy.sh
      timeout: 60
      runas: root